name: fluttership
description: A Project Where I Share The Things I Love To Share

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0" 
  #I̶ d̶o̶n̶'̶t̶ u̶s̶e̶ n̶u̶l̶l̶s̶a̶f̶e̶t̶y̶ t̶o̶ u̶s̶e̶ n̶u̶l̶l̶s̶a̶f̶t̶e̶t̶y̶ r̶e̶p̶l̶a̶c̶e̶ 2̶.̶7̶.̶0̶ w̶i̶t̶h̶ 2̶.̶1̶2̶.̶0̶

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0
  measured_size: ^1.0.0
  equatable: ^2.0.3
  cached_network_image: ^3.0.0
  firebase_storage: ^8.0.4
  image_cropper: ^1.4.0
  image_picker: ^0.7.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.2.0
  

flutter_native_splash:
  color: "#0063dd"
  image: assets/logo.png #u must place logo.png in your assets folder
  android: true
  ios: true



flutter:
  uses-material-design: true
  assets:
  - assets/
